/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TradingRouteImport } from './routes/trading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/market': typeof MarketRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/trading': typeof TradingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/market': typeof MarketRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/trading': typeof TradingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/market': typeof MarketRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/trading': typeof TradingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/market' | '/portfolio' | '/settings' | '/trading'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/market' | '/portfolio' | '/settings' | '/trading'
  id: '__root__' | '/' | '/market' | '/portfolio' | '/settings' | '/trading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketRoute: typeof MarketRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  TradingRoute: typeof TradingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketRoute: MarketRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  TradingRoute: TradingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
